### ISSUE TITLE
error on https

### ISSUE THREAD

**Issue by cordoval** [kevinsimper/wkhtmltoimage-docker#1]
it seems when you go to https the wkhtmltoimage does not work well

``` yaml
- docker run -it --net=host -v $CIRCLE_ARTIFACTS:/images kevinsimper/wkhtmltoimage https://0.0.0.0 /images/frontpage.png || true
```

does not work

```
Starting

Docker Host:  172.16.254.1

Loading page (1/2)

Error: Failed loading page https://0.0.0.0 (sometimes it will work just to ignore this error with --load-error-handling ignore)

Exit with code 1 due to network error: ConnectionRefusedError
```

**Comment by kevinsimper** [comment]
You got a `ConnectionRefusedError` so that means the webserver refused the connection.

Did you also configure it to serve https?

**Comment by cordoval** [comment]
yes the app is serving over https for sure, that is what i deploy and it works

**Comment by kevinsimper** [comment]
Yes, but your webserver still refused the connection, so it must works differently on CircleCI

This https example works fine 😄 

```
$ docker run -it --net=host -v $(pwd):/images kevinsimper/wkhtmltoimage https://kevinsimper.dk /images/google.png
```

**Comment by cordoval** [comment]
the difference is on the how it is referenced inside circleci, for instance it was before http://0.0.0.0:80, then i changed it to https://0.0.0.0 presumably it should have kept on working

**Comment by kevinsimper** [comment]
How should it do that? You changed the port by changing the protocol?

**Comment by cordoval** [comment]
https automatically serves on port 443 by default

**Comment by kevinsimper** [comment]
Yes, and your webserver refused the connection on port 443 :blush:
